---
- name: "Deploy Jenkins"
  hosts: "{{ tower_env | default([]) }}"
  gather_facts: true
  become: true
  become_method: "ansible.builtin.sudo"

  tasks:

    - name: "Install Docker"
      when: inv_install_docker | default(false)
      block:
        - name: "Include labocbz.prepare_host"
          tags:
            - "labocbz.prepare_host"
          ansible.builtin.include_role:
            name: "labocbz.prepare_host"

        - name: "Include labocbz.install_docker"
          tags:
            - "labocbz.install_docker"
          vars:
            install_docker__portainer: "{{ inv_install_docker__portainer }}"
            install_docker__portainer_http_port: "{{ inv_install_docker__portainer_http_port }}"
            install_docker__portainer_https_port: "{{ inv_install_docker__portainer_https_port }}"
            install_docker__portainer_agent_port: "{{ inv_install_docker__portainer_agent_port }}"
            install_docker__portainer_container_name: "{{ inv_install_docker__portainer_container_name }}"
            install_docker__portainer_volume_name: "{{ inv_install_docker__portainer_volume_name }}"
            install_docker__portainer_ssl: "{{ inv_install_docker__portainer_ssl }}"
            install_docker__portainer_ssl_volume_name: "{{ inv_install_docker__portainer_ssl_volume_name }}"
            install_docker__portainer_ssl_key: "{{ inv_install_docker__portainer_ssl_cert }}"
            install_docker__watchtower: "{{ inv_install_docker__watchtower }}"
            install_docker__watchtower_poll_interval: "{{ inv_install_docker__watchtower_poll_interval }}"
            install_docker__watchtower_cleanup: "{{ inv_install_docker__watchtower_cleanup }}"
            install_docker__watchtower_include_restarting: "{{ inv_install_docker__watchtower_include_restarting }}"
            install_docker__watchtower_include_stopped: "{{ inv_install_docker__watchtower_include_stopped }}"
            install_docker__watchtower_no_restart: "{{ inv_install_docker__watchtower_no_restart }}"
            install_docker__portainer_address: "{{ inv_install_docker__portainer_address }}"
            install_docker__handle_clean: "{{ inv_install_docker__handle_clean }}"
            install_docker__clean_cron_file: "{{ inv_install_docker__clean_cron_file }}"
            install_docker__clean_weekday: "{{ inv_install_docker__clean_weekday }}"
            install_docker__clean_minute: "{{ inv_install_docker__clean_minute }}"
            install_docker__clean_hour: "{{ inv_install_docker__clean_hour }}"
            install_docker__insecure_registries: "{{ inv_install_docker__insecure_registries }}"
          ansible.builtin.include_role:
            name: "labocbz.install_docker"

    - name: "Install Jenkins"
      when: inv_install_jenkins | default(false)
      block:
        - name: "Include labocbz.prepare_host"
          tags:
            - "labocbz.prepare_host"
          vars:
            prepare_host__system_users: "{{ inv_prepare_host__jenkins_system_users }}"
          ansible.builtin.include_role:
            name: "labocbz.prepare_host"

        - name: "Include labocbz.install_jenkins"
          tags:
            - "labocbz.install_jenkins"
          vars:
            install_jenkins__user: "{{ inv_install_jenkins__user }}"
            install_jenkins__group: "{{ inv_install_jenkins__group }}"
            install_jenkins__home: "{{ inv_install_jenkins__home }}"
            install_jenkins__container_name: "{{ inv_install_jenkins__container_name }}"
            install_jenkins__host: "{{ inv_install_jenkins__host }}"
            install_jenkins__port: "{{ inv_install_jenkins__port }}"
            install_jenkins__client_port: "{{ inv_install_jenkins__client_port }}"
          ansible.builtin.include_role:
            name: "labocbz.install_jenkins"

    - name: "Install Apache2"
      when: inv_install_apache | default(false)
      block:
        - name: "Include labocbz.prepare_host"
          tags:
            - "labocbz.prepare_host"
          vars:
            prepare_host__system_users: "{{ inv_prepare_host__apache_system_users }}"
          ansible.builtin.include_role:
            name: "labocbz.prepare_host"

        - name: "Include labocbz.add_certificates"
          tags:
            - "labocbz.add_certificates"
          loop: "{{ inv_add_apache_confs__configurations_cert_bundles }}"
          loop_control:
            loop_var: bundle
          when: inv_add_apache_confs__configurations_cert_bundles is defined
          vars:
            add_certificates__bundle_name: "{{ bundle.name }}"
            add_certificates__bundle_type: "{{ bundle.type }}"
            add_certificates__bundle_src: "{{ bundle.src }}"
            add_certificates__bundle_dest: "{{ bundle.dest }}"
            add_certificates__bundle_src_user: "{{ bundle.src_user }}"
            add_certificates__bundle_src_password: "{{ bundle.src_password }}"
            add_certificates__bundle_dest_user: "{{ bundle.dest_user }}"
            add_certificates__bundle_dest_group: "{{ bundle.dest_group }}"
            add_certificates__bundle_dest_mode: "{{ bundle.dest_mode }}"
          ansible.builtin.include_role:
            name: "labocbz.add_certificates"

        - name: "Include labocbz.install_apache"
          tags:
            - "labocbz.install_apache"
          vars:
            install_apache__https_listen_port: "{{ inv_install_apache__https_listen_port }}"
            install_apache__http_listen_port: "{{ inv_install_apache__http_listen_port }}"
            install_apache__modules: "{{ inv_install_apache__modules }}"
            install_apache__enable_qos: "{{ inv_install_apache__enable_qos }}"
            install_apache__enable_security: "{{ inv_install_apache__enable_security }}"
            install_apache__security_core_version: "{{ inv_install_apache__security_core_version }}"
            install_apache__remove_all_vhosts: "{{ inv_install_apache__remove_all_vhosts }}"
            install_apache__loglevel: "{{ inv_install_apache__loglevel }}"
            install_apache__security_version: "{{ inv_install_apache__security_version }}"
            install_apache__enable_evasive: "{{ inv_install_apache__enable_evasive }}"
            install_apache__enable_pagespeed: "{{ inv_install_apache__enable_pagespeed }}"
            install_apache__enable_prefork: "{{ inv_install_apache__enable_prefork }}"
          ansible.builtin.include_role:
            name: "labocbz.install_apache"

        - name: "Include labocbz.add_apache_confs"
          tags:
            - "labocbz.add_apache_confs"
          vars:
            add_apache_confs__http_listen_port: "{{ inv_add_apache_confs__http_listen_port }}"
            add_apache_confs__https_listen_port: "{{ inv_add_apache_confs__https_listen_port }}"
            add_apache_confs__ldap_url: "{{ inv_add_apache_confs__ldap_url }}"
            add_apache_confs__ldap_port: "{{ inv_add_apache_confs__ldap_port }}"
            add_apache_confs__ldap_dc: "{{ inv_add_apache_confs__ldap_dc }}"
            add_apache_confs__auth_ldap_url: "{{ inv_add_apache_confs__auth_ldap_url }}"
            add_apache_confs__custom_ldap_base_header: "{{ inv_add_apache_confs__custom_ldap_base_header }}"
            add_apache_confs__webmaster: "{{ inv_add_apache_confs__webmaster }}"
            add_apache_confs__request_body: "{{ inv_add_apache_confs__request_body }}"
            add_apache_confs__security_body_limit: "{{ inv_add_apache_confs__security_body_limit }}"
            add_apache_confs__ssl_files_path: "{{ inv_add_apache_confs__ssl_files_path }}"
            add_apache_confs__confs_path: "{{ inv_add_apache_confs__confs_path }}"
            add_apache_confs__base_document_root: "{{ inv_add_apache_confs__base_document_root }}"
            add_apache_confs__configurations: "{{ inv_add_apache_confs__configurations }}"
          ansible.builtin.include_role:
            name: "labocbz.add_apache_confs"

        - name: "Include labocbz.add_logrotate_confs"
          tags:
            - "labocbz.add_logrotate_confs"
          vars:
            add_logrotate_confs__files: "{{ inv_add_logrotate_confs__apache_configurations }}"
          ansible.builtin.include_role:
            name: "labocbz.add_logrotate_confs"

        - name: "Block all trafic from other hosts on port Jenkins (disable acces to Jenkins without Apache2)"
          ansible.builtin.iptables:
            chain: "INPUT"
            protocol: "tcp"
            destination_port: "{{ inv_install_jenkins__port }}"
            jump: "DROP"
            source: "! 127.0.0.1"
            comment: "Force external user to use jenkins"

- name: "Deploy Jenkins Agents"
  hosts: "{{ tower_env | default([]) }}"
  gather_facts: true
  become: true
  become_method: "ansible.builtin.sudo"

  tasks:
    - name: "Deploy Jenkins Agent"
      when: inv_install_jenkins_agent | default(false)
      block:
        - name: "Include labocbz.prepare_host"
          tags:
            - "labocbz.prepare_host"
          ansible.builtin.include_role:
            name: "labocbz.prepare_host"

        - name: "Include labocbz.add_certificates"
          tags:
            - "labocbz.add_certificates"
          loop: "{{ inv_install_jenkins_agent__cert_bundles }}"
          loop_control:
            loop_var: bundle
          when: inv_install_jenkins_agent__cert_bundles is defined
          vars:
            add_certificates__bundle_name: "{{ bundle.name }}"
            add_certificates__bundle_type: "{{ bundle.type }}"
            add_certificates__bundle_src: "{{ bundle.src }}"
            add_certificates__bundle_dest: "{{ bundle.dest }}"
            add_certificates__bundle_src_user: "{{ bundle.src_user }}"
            add_certificates__bundle_src_password: "{{ bundle.src_password }}"
            add_certificates__bundle_dest_user: "{{ bundle.dest_user }}"
            add_certificates__bundle_dest_group: "{{ bundle.dest_group }}"
            add_certificates__bundle_dest_mode: "{{ bundle.dest_mode }}"
          ansible.builtin.include_role:
            name: "labocbz.add_certificates"

        - name: "Include labocbz.install_java"
          tags:
          - "labocbz.install_java"
          vars:
            install_java__version: "{{ inv_install_java__version }}"
            install_java__cpu_architecture: "{{ inv_install_java__cpu_architecture }}"
            install_java__version_is_default: true
          ansible.builtin.include_role:
            name: "labocbz.install_java"

        - name: "Include labocbz.install_jenkins_agent__"
          tags:
            - "labocbz.install_jenkins_agent"
          vars:
            install_jenkins_agent__user: "{{ inv_install_jenkins_agent__user }}"
            install_jenkins_agent__group: "{{ inv_install_jenkins_agent__group }}"
            install_jenkins_agent__password: "{{ inv_install_jenkins_agent__password }}"
            install_jenkins_agent__docker_based: "{{ inv_install_jenkins_agent__docker_based }}"
            install_jenkins_agent__name: "{{ inv_install_jenkins_agent__name }}"
            install_jenkins_agent__home: "{{ inv_install_jenkins_agent__home }}"
            install_jenkins_agent__master_remote: "{{ inv_install_jenkins_agent__master_remote }}"
            install_jenkins_agent__jar: "{{ inv_install_jenkins_agent__jar }}"
            install_jenkins_agent__secret: "{{ inv_install_jenkins_agent__secret }}"
            install_jenkins_agent__log_path: "{{ inv_install_jenkins_agent__log_path }}"
            install_jenkins_agent__ca: "{{ inv_install_jenkins_agent__ca }}"
            install_jenkins_agent__https_check: "{{ inv_install_jenkins_agent__https_check }}"
            install_jenkins_agent__basic_auth_login: "{{ inv_install_jenkins_agent__basic_auth_login }}"
            install_jenkins_agent__basic_auth_password: "{{ inv_install_jenkins_agent__basic_auth_password }}"
            install_jenkins_agent__basic_auth: "{{ inv_install_jenkins_agent__basic_auth }}"
          ansible.builtin.include_role:
            name: "labocbz.install_jenkins_agent"
